# Generated by Django 4.2 on 2026-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyqquestion",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pyqquestion",
            name="options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
