# Generated by Django 5.2.10 on 2026-02-21 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0003_course_university_alter_databankdocument_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyqsession",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="databank.module",
            ),
        ),
        migrations.AlterField(
            model_name="pyqsession",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="databank.subject",
            ),
        ),
    ]
