# Generated by Django 5.2.10 on 2026-02-21 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0004_pyqsession_module_alter_pyqsession_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBankQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("solution", models.TextField(blank=True)),
                ("repetition_count", models.IntegerField(default=1)),
                ("last_seen_years", models.JSONField(default=list)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_questions",
                        to="databank.semester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("mid", "Mid Semester"),
                            ("end", "End Semester"),
                            ("supple", "Supplementary"),
                        ],
                        default="end",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="question_papers/")),
                ("is_analyzed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_papers",
                        to="databank.course",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_papers",
                        to="databank.semester",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_papers",
                        to="databank.university",
                    ),
                ),
            ],
        ),
    ]
