# Generated by Django 5.2.10 on 2026-02-21 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_per_1k_tokens",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("max_tokens", models.IntegerField(default=4096)),
                ("temperature", models.FloatField(default=0.7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("summarize", "Summarize"),
                            ("flashcards", "Generate Flashcards"),
                            ("solve_pyq", "Solve PYQ"),
                            ("one_night_prep", "One Night Prep"),
                            ("ocr", "OCR Extraction"),
                            ("image_to_notes", "Image to Notes"),
                            ("solve_image", "Solve Question from Image"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_text", models.TextField(blank=True)),
                ("output_text", models.TextField(blank=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("response_time_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_aireques_user_id_0890a7_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="ai_aireques_endpoin_da34d6_idx",
                    ),
                ],
            },
        ),
    ]
