# Generated by Django 5.2.8 on 2026-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_last_ai_reset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_ai_reset",
            field=models.DateField(auto_now_add=True),
        ),
    ]
