# Generated by Django 4.2 on 2026-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_last_ai_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_streak_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
