# Generated by Django 4.2 on 2026-02-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_current_streak_user_last_streak_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
    ]
