# Generated by Django 5.2.10 on 2026-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_blacklisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprofile",
            name="career_path",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="upcoming_exams",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
