# Generated by Django 5.2.10 on 2026-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_academicprofile_career_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicprofile",
            name="career_path",
        ),
        migrations.RemoveField(
            model_name="academicprofile",
            name="upcoming_exams",
        ),
        migrations.AddField(
            model_name="user",
            name="career_path",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="upcoming_exams",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
