# Generated by Django 5.2.10 on 2026-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_academicprofile_career_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="course_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
