# Generated by Django 4.2 on 2026-02-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
